export const SERVER_URL = import.meta.env.VITE_SERVER_URL;
export const ROLES = {
  ADMIN: "admin",
  CONTENT_REVIEWER: "content reviewer",
  MODERATOR: "moderator",
  CONTRIBUTOR: "contributor",
};
export const TOOLBAR_BUTTONS = [
  { key: "mod+b", mark: "bold", type: "mark" },
  { key: "mod+i", mark: "italic", type: "mark" },
  { key: "mod+u", mark: "underline", type: "mark" },
  { key: "mod+shift+s", mark: "strikethrough", type: "mark" },
  { key: "mod+`", mark: "code", type: "mark" },
  { block: "list-ul", type: "block" },
  { block: "list-ol", type: "block" },
];

export const PREFERENCES = [
  "Physics",
  "Math",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Engineering",
  "Psychology",
  "Sociology",
  "Economics",
  "Political Science",
  "History",
  "Philosophy",
  "Literature",
  "Art",
  "Music",
  "Dance",
  "Theater",
  "Film",
  "Photography",
  "Culinary Arts",
  "Fashion",
  "Architecture",
  "Urban Planning",
  "Environmental Science",
  "Animal watching",
  "Aquascaping",
  "Board games",
  "Calligraphy",
  "Candle making",
  "Chess",
  "Coding",
  "Cosplay",
  "Cryptocurrency",
  "Debate",
  "Digital art",
  "DIY projects",
  "Dog training",
  "Escape rooms",
  "Genealogy",
  "Geocaching",
  "Hiking",
  "Historical reenactment",
  "International cuisine",
  "Jewelry making",
  "Juggling",
  "Karaoke",
  "Knitting",
  "Learning new languages",
  "Magic tricks",
  "Meditation",
  "Metalworking",
  "Model building",
  "Mushroom foraging",
  "Origami",
  "Parkour",
  "Penmanship",
  "Poetry",
  "Puzzles",
  "Quilting",
  "Robotics",
  "Scuba diving",
  "Sign language",
  "Soap making",
  "Stand-up comedy",
  "Stargazing",
  "Street art",
  "Sustainable living",
  "Tabletop RPGs",
  "Urban exploration",
  "Vintage fashion",
  "Wildlife photography",
  "Woodworking",
  "Yoga",
  "Preference for silence or constant noise",
  "Introverted or extroverted",
  "Logical or intuitive",
  "Organized or spontaneous",
  "Risk-taker or cautious",
  "Early riser or night owl",
  "Morning person or afternoon person",
  "Dog person or cat person",
  "City dweller or nature lover",
  "Minimalist or collector",
  "Collecting insects",
  "Competitive eating",
  "Extreme ironing",
  "Fire spinning",
  "Frog breeding",
  "Metal detecting",
  "Pet rock collecting",
  "Professional whistling",
  "Vegetable carving",
];
